#ifndef __SDK_WAFFLE_COMPONENT_H_
#define __SDK_WAFFLE_COMPONENT_H_

#ifdef  _BUILD_WAFFLE_COMPONENT_
#ifdef _MSC_VER
#define WAFFLE_COMPONENT_FUNCTION
#else
#define WAFFLE_COMPONENT_FUNCTION LIBRARY_EXPORT
#endif
#else
#define WAFFLE_COMPONENT_FUNCTION LIBRARY_IMPORT
#endif

WAFFLE_COMPONENT_FUNCTION SIZE_T WINAPI ComponentInit(
    _In_    LPWAFFLE_PROCESS_SETTING lpstProcessSetting
    );

typedef SIZE_T(WINAPI *LPCOMPONENTINIT)(
    _In_    LPWAFFLE_PROCESS_SETTING lpstProcessSetting
    );

#endif /* __SDK_WAFFLE_COMPONENT_H_ */